services:
    vinny.wysiwyg.text_formatter.converter:
        class: vinny\wysiwyg\text_formatter\converter
        arguments:
            - '@dbal.conn'
            - '@config'
            - '%core.root_path%'
            - '@text_formatter.parser'
            - '@language'

    vinny.wysiwyg.controller:
        class: vinny\wysiwyg\controller\wysiwyg_controller
        arguments:
            - '@request'
            - '@vinny.wysiwyg.text_formatter.converter'
            - '@config'
            - '@user'

    vinny.wysiwyg.listener:
        class: vinny\wysiwyg\event\main_listener
        arguments:
            - '@request'
            - '@vinny.wysiwyg.text_formatter.converter'
            - '@config'
            - '@user'
            - '@template'
            - '@controller.helper'
        tags:
            - { name: event.listener }
